Fix missing struct member 's6_addr32' on OSX
Like FreeBSD, `in6_addr` doesn't have a struct member called `s6_addr32` on Mac OS X.

This commit adds OSX to the controlled group that replaces `s6_addr32` with `__u6_addr.__u6_addr32`.

The error thrown was this:

```
dns.c:520:11: error: no member named 's6_addr32' in 'struct in6_addr'
         &IP4ADDR(&ip_addr),
          ^~~~~~~~~~~~~~~~~
./passivedns.h:294:28: note: expanded from macro 'IP4ADDR'
```